### ISSUE TITLE
Set Color Temperature for RGB Bulbs  doesnt work

### ISSUE THREAD

**Issue by scobby** [treban/pimatic-raspbee#17] opened 2018-05-29 13:03 UTC
Hi Treban,
the color temperature for RGB (tradfri rgb bulb) doesnt work.

for example:
setCT?colorCode=81

or via the frontend slider for color temperature.

cany you fix this?

**Comment by treban** [comment] 2018-05-29 13:26
I will take a look at it

**Comment by treban** [comment] 2019-07-04 13:38
The problem is, that die **tradfri** RGB Bulb does not support color temperature out of the box 
over the deconz api. 

I can't change the color-temperature over the deconz website either. 

deconz knows 3 types of lights 
[see here](https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Lights)

plugin device type | features | deconz device type
-- | -- | --
RaspBeeCT | change temperature | Color temperature light
RaspBeeRGB | change color | Color light
RaspBeeRGBCT | change color and temperature | Extended color light

I will check if i can implement a transformation formula.

**Comment by 00lex** [comment] 2019-07-15 16:48
now I run into the same issue https://github.com/michbeck100/pimatic-hap/issues/80#issuecomment-511478360

can you give me a hint? 

```
set color rgb Paradieslicht2 to to #121212
set color rgbct Paradieslicht2 to to #121212
```
does not work :( I just get "the" from "set color rgb"
<img width="172" alt="Bildschirmfoto 2019-07-15 um 21 37 50" src="https://user-images.githubusercontent.com/39100562/61243715-e734ec80-a748-11e9-9277-6976cc8459a9.png">

**Comment by 00lex** [comment] 2019-07-15 20:08
no solution, but im a little closer. here my observation:

- the correct and proposed class for color bulb is RGBCT. but then we can't write rules like `set color rgb Paradieslicht2 to to #121212` ; RGBCT bulbs seems not to be recognized from the rule engine (HomeKit is full supported)

- if I change the class from RGBCT to RGB when I add a new bulb, I can write the mentioned rule and HomeKit is also working but the the slider for color temp is missing in the dashboard. strangely in homekit I can set the color temperature 
<img width="823" alt="Bildschirmfoto 2019-07-15 um 22 00 19" src="https://user-images.githubusercontent.com/39100562/61245323-84455480-a74c-11e9-8511-02889b1614aa.png">

I don't know how to add RaspBeeRGBCT to action.coffee :(

its a little OT, but why do you use hex values? if I take a look at the variables, I see regular numbers

**Comment by treban** [comment] 2019-07-15 21:52
@00lex 
you're right 
the RGBCT devices class is not completely covered by the rules.
i will fix that soon!
for the hap plugin i am preparing a pull request,
so that support is fully implemented for CT-only bulbs and sensors.

the rgb hex value is historically related :) 
I will add an action provider with hue and sat parameters.

**Comment by 00lex** [comment] 2019-07-15 22:38
> I will add an action provider with hue and sat parameters.

that was just a question without intentions. but good, thank you!

**Comment by 00lex** [comment] 2019-07-16 13:22
okay with the last update this works to: 
`dim raspbee ParadieslichtRGBCT to 90 and set color rgb ParadieslichtRGBCT to #BF2413`

I can live with that and I´m happy. 
my old workflow with hue-zll was set a color and read the values from variables to write rules. 






now I set a color, read the HSV values from dashboard: 
<img width="618" alt="Bildschirmfoto 2019-07-16 um 15 13 14" src="https://user-images.githubusercontent.com/39100562/61297571-ccac5300-a7dc-11e9-8e63-3d3a6ca1fa07.png">

and then convert them on this site to the hex value for the rule: 
https://www.rapidtables.com/convert/color/hsv-to-rgb.html
<img width="647" alt="Bildschirmfoto 2019-07-16 um 15 18 07" src="https://user-images.githubusercontent.com/39100562/61297651-f1082f80-a7dc-11e9-84a3-fb0561468341.png">

its not ideal, but it works

**Comment by 00lex** [comment] 2019-07-16 13:30
wait I make a mistake! I can only read the HSV value from hue-zll bulbs, not from raspbee-bulbs

**Comment by treban** [comment] 2019-07-16 13:45
i will rebuild the color management and change from rgb to hsv. 
then it's consistent.

**Comment by 00lex** [comment] 2019-07-16 20:46
okay perfect! 

in this context, I remember there's another benefit if you change HEX to HSV. 
https://forum.pimatic.org/topic/2983/shuffle-color/4
hope you are a disco guy :) 

I think the raspbee-plugin in this state makes hue-zll and the tradfri plugin obsolete 👍

**Comment by 00lex** [comment] 2019-07-18 09:32
Feedback: 

ok, i edit my config to transferee all my rules from the hue-zll to raspbee plugin.
raspbee has another behavior. if a bulb is tuned off with the following execution:
`dim raspbee Paradieslicht to $dimlv_paradies and set color rgb Paradieslicht to #8A8B7A`,
I get an error because the bulb was turned off.

to handle this, I need to add a delay for the second action: 
`dim raspbee Paradieslicht to $dimlv_paradies and set color rgb Paradieslicht to #8A8B7A after 1s`

everything else works as before. thank you! 
EDIT: 
that's OT but maybe interesting for you in case v2 bricks things in your plugin some day. 

and this is OT too, but its a very cool hack for aqara body motion sensor. 
I've done this with 5 and it works since one week perfect 
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1671

**Comment by treban** [comment] 2019-07-24 08:57
@00lex new beta is published 
pimatic-raspbee@0.1.2 = pimatic-raspbee@beta
can you check it?

* GUI shows now hsv values 
* setHue and setSat action provider 
* RGB bulb has now also a color temperatur slider 

tradfri bulbs are `Color light`
 -> no native color temperature support , implemented by 
philips hue are `Extended color light?
 -> native color temperature support

pimatic Device type | Feature | Deconz Resource Type
-- | -- | --
RaspBeeRGB | change color and temperature | Color light
RaspBeeRGBCT | change color and temperature | Extended color light

**Comment by 00lex** [comment] 2019-07-24 10:52
> philips hue are `Extended color light?

I think, but im not sure.

the new versions has no for me notable issues. 
the update itself runs without issues, first start without unexpected errors, rules can be written as with hue-zll and values of hue+saturation match the expected final color. 

instal of (v0.1.1):
`dim raspbee Fensterbrett to $dimlv_salon +10 transition time 10s and set color rgb Fensterbrett to #8A8B7A after 1s`

we can no write again (v0.1.2):
`dim raspbee Fensterbrett to $dimlv_salon +10 transition time 10s and set color Fensterbrett to hue 12.85 and sat 55 after 1s`

KUDOS! I just test it with a hue bulb and a hue light stripe. 

just on thing. maybe for documentation. if I bulb is turned off, you have to put a small delay after the second action if the rule dim AND set a color. else you get a error and the color will not change. this behavior doesn't exist with hue-zll, but I don't see a problem to handle this with a delay.

**Comment by 00lex** [comment] 2019-07-27 11:15
from my site you can push the release button and close this issue 👍

**Comment by treban** [comment] 2019-08-02 08:09
0.1.2 released

**Closed as completed by treban** 2019-08-02 08:09 UTC
Labels: enhancement
